# Generated by Django 3.2.4 on 2021-06-16 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('raza', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='raza')),
                ('sexo', models.CharField(max_length=10, verbose_name='sexo animal')),
                ('edad', models.CharField(blank=True, max_length=20, null=True, verbose_name='edad')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
