# Generated by Django 3.2.4 on 2021-06-26 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='rut')),
                ('razon_social', models.CharField(max_length=50, verbose_name='razon_social')),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de servicio')),
                ('nombreServicio', models.CharField(max_length=50, verbose_name='nombre del servicio')),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='Servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio'),
        ),
    ]
